apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-observable-api
spec:
  revisionHistoryLimit: 12
  minReadySeconds: 30
  progressDeadlineSeconds: 900
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 3
