apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-observable-api
spec:
  revisionHistoryLimit: 6
  minReadySeconds: 10
  progressDeadlineSeconds: 420
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
