apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: everything-backend

resources:
  - namespace.yaml
  - configmaps
  - deployments
  - services
  - ingress

images:
  - name: docker.io/minio/minio
    newTag: RELEASE.2025-09-07T16-13-09Z
